services:
  mysql:
    image: mysql:8.4
    container_name: muslim-pro-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: muslim_pro
      MYSQL_USER: muslim_pro_user
      MYSQL_PASSWORD: muslim_pro_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
